# Generated by Django 2.2 on 2024-04-15 06:35

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Jacky', max_length=10000)),
                ('content', models.TextField()),
                ('path', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '网站归档',
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='sitemessage',
            name='modified',
        ),
        migrations.AlterField(
            model_name='friend',
            name='main',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='friend',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='friend',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
