# Generated by Django 2.2 on 2024-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
