# Generated by Django 2.2 on 2024-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_remove_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
