# Generated by Django 2.2 on 2024-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_timelineevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='author',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='created',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='path',
        ),
        migrations.AddField(
            model_name='timeline',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timeline',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
