# Generated by Django 2.2 on 2024-04-27 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0010_auto_20240427_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ('-created',), 'verbose_name_plural': '网站归档'},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='title',
        ),
        migrations.AddField(
            model_name='timeline',
            name='author',
            field=models.CharField(blank=True, default='Jacky', max_length=10000),
        ),
        migrations.AddField(
            model_name='timeline',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeline',
            name='path',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
