# Generated by Django 2.2 on 2024-04-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_auto_20240427_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
