# Generated by Django 2.2 on 2024-04-27 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_delete_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Jacky', max_length=10000)),
                ('content', models.TextField()),
                ('path', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '网站归档',
                'ordering': ('-created',),
            },
        ),
    ]
