# Generated by Django 2.2 on 2024-04-27 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0013_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='author',
            field=models.CharField(blank=True, default='Wang', max_length=10000),
        ),
    ]
