# Generated by Django 2.2 on 2024-04-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0014_auto_20240427_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
