# Generated by Django 2.2 on 2024-04-27 13:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0017_auto_20240427_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('main', ckeditor.fields.RichTextField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '友链',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
