# Generated by Django 2.2 on 2024-05-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0018_auto_20240427_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteMessage',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
