# Generated by Django 2.2 on 2024-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20240427_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVisit',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article\\2024-04-27_18-18-26'),
        ),
    ]
