# Generated by Django 2.2 on 2024-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20240425_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article\\2024-04-25_10-57-07'),
        ),
    ]
