# Generated by Django 2.2 on 2024-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20240427_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article\\2024-04-27_21-18-59'),
        ),
    ]
