# Generated by Django 2.2 on 2024-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20240430_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article\\2024-04-30_17-19-16'),
        ),
    ]
