# Generated by Django 2.2 on 2024-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20240430_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article\\2024-04-30_18-48-18'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
