# Generated by Django 2.2 on 2024-04-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wechat',
        ),
    ]
