# Generated by Django 2.2 on 2024-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
